spring.application.name=gofit
spring.datasource.url=jdbc:mariadb://localhost:3306/gofit
spring.datasource.username=root
spring.datasource.password=root
server.port=8083
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true